# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFQssEAKwhZ-j3uC2z_JYf0EIqxzRgDi
"""

import requests
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Create a simple dataset for binary classification
# Replace this with your own dataset if you have one
# X = input features, y = corresponding labels (0 or 1)
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 0]

# Convert the data to numpy arrays
X = np.array(X)
y = np.array(y)

# Create a simple feedforward neural network
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
optimizer = Adam(learning_rate=0.01)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=100, batch_size=1)

# Make predictions
predictions = model.predict(X)

# Print the predictions
for i in range(len(X)):
    print(f"Input: {X[i]}, Prediction: {predictions[i][0]}")




url = "https://odds.p.rapidapi.com/v4/sports"

querystring = {"all":"true"}

headers = {
	"X-RapidAPI-Key": "e4d0a74bffmsh7c86216533dbd16p114010jsne61e27952fb7",
	"X-RapidAPI-Host": "odds.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)